src/locallibrary/catalog/urls.py
from django.urls import path
from . import views

# how does book_list.html get rendered?

# Note: This awkward path for the template location isn't a misprint — the generic views look for templates in 
# /application_name/the_model_name_list.html (catalog/book_list.html in this case) inside the application's 
# /application_name/templates/ directory (/catalog/templates/).

# our model name is called BookListView; thus, to camel_case, book_list(_view).


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [   
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('allbooks/', views.BorrowedBooksListView.as_view(), name='all-borrowed')
]

src/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application 
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

src/locallibrary/catalog/models.py
from datetime import date

from django.db import models
#we make the auth user object available to the models below
from django.contrib.auth.models import User

# Create your models here.

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

from django.urls import reverse # Used to generate URLs by reversing the URL patterns

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author here is declared as a string rather than object because it hasn't been declared yet in the file
    # (note how it still works )
    # this relationship is used elsewhere, as are manytomany and onetoone; foreignkey is equivalent to onetomany
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    #as per challenge.
    #here, we assume a book is only one language (just as we assume a book only has one author)
    #better as an object?
    language = models.CharField('Language', max_length=100, help_text='Enter a locale as per <a href="https://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes">this post</a>')
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">'
                            'ISBN number</a>')
    
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'

import uuid # Required for unique book instances

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    #see https://www.programiz.com/python-programming/property
    #and https://www.programiz.com/python-programming/decorator
    #this is equivalent to is_overdue = property(is_overdue)
    #property() allows us to easily handle attributes of an object
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        # We look at urls.py for this
        # The HTML files ask for author.get_absolute_url()
        # This returns the integer ID of this author using the url pattern with
        # the name `author-detail`
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

src/locallibrary/catalog/views.py
from django.shortcuts import render

# Create your views here.
from catalog.models import Book, Author, BookInstance, Genre

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # here we create a filter of titles that contain the case insensitive word "China"
    # this is done with the field `title` and using __icontains as the filter
    # see https://docs.djangoproject.com/en/3.1/topics/db/queries/
    num_books_from_china = Book.objects.filter(title__icontains='China').count()
    
    # The 'all()' is implied by default.    
    num_authors = Author.objects.count()
    
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

from django.views import generic

class BookListView(generic.ListView):
    model = Book
    #if, perhaps, you wanted to list five books with war
    #context_object_name = 'my_book_list'   # your own name for the list as a template variable
    #queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    #template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location
    
    #this caps the max books shown at once on the All Books page to a number
    #additional pages are done with GET query strings, e.g., /catalog/books/?page=2
    paginate_by = 1

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    #we could paginate here but i dont have enough authors

class AuthorDetailView(generic.DetailView):
    model = Author



from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    #This has exactly the same redirect behaviour as the login_required decorator.
    #You can also specify an alternative location to redirect the user to if they are not authenticated (login_url),
    # and a URL parameter name instead of "next" to insert the current absolute path (redirect_field_name).
    #there is no need to do that here since ridirecting to /login is already desired
    '''
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    '''
    
    #apart from pagination restricting the returned count to 10
    #here we filter the results returned by borrower, then by those with a status of on loan
    #then we sort by the due back date
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

#this mixin allows us to restrict views to those with specific permissions
#(note that admins/superusers are treated as having ALL permissions)
#decorators can be used as well, though this can be at the cost of some flexibility
#for example, changing a view based on individual permissions; then additional views would need to be
#declared
from django.contrib.auth.mixins import PermissionRequiredMixin

#orignally this inherited LoginRequiredMixin as well...
#but that broke the page and always routed to a 403
class BorrowedBooksListView(PermissionRequiredMixin,LoginRequiredMixin,generic.ListView):
    #notice how there is no explicit redirect to login.html if lacking permissions
    #see https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication#Login_template
    #if the user is logged in but lacking permissions, it will throw 403 forbidden at them
    #see https://docs.djangoproject.com/en/3.1/ref/views/ for what happens
    permission_required = 'catalog.can_mark_returned'
    #again, not needed
    '''
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    '''
   
    model = BookInstance
    template_name ='catalog/borrowed_books_list.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


src/locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <!--
      this is based on BookDetailView, which exposes a single Book object as the `book`.
      from there, we can then take the fields of the model as shown below

      from mdn:
      That's it! All you need to do now is create a template called /locallibrary/catalog/templates/catalog/book_detail.html, 
      and the view will pass it the database information for the specific Book record extracted by the URL mapper. 
      Within the template you can access the list of books with the template variable named object OR book 
      (i.e. generically "the_model_name").
  -->
<h1>Author: {{ author }}</h1>

<p><strong>Date of birth:</strong> {{ author.date_of_birth }}</a></p> 
{% if author.date_of_death %}<p><strong>Date of death:</strong> {{ author.date_of_death }}</p>{% endif %}


<div style="margin-left:20px;margin-top:20px">
  <h4>Books</h4>
  <!--
    author.book_set.all is a django-constructed iterable of every Book object associated with this Author
    note the `_set`, which is what actually produces the iterable
    then .all returns an iterable of every object
  -->
  {% for book in author.book_set.all %}
    <b><a href="{{ book.get_absolute_url }}">{{book}}</a> ({{book.bookinstance_set.all.count}})</b>
    <p>{{book.summary}}</p>
  {% endfor %}
</div>
{% endblock %}

src/locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <!--{{ author.last_name }}, {{ author.first_name }} is an alternative
        but using the object itself causes an implicit string conversion, where __str__ is called
        and since we defined our own __str__, it returns last_name, first_name as is-->
        <a href="{{ author.get_absolute_url }}">{{ author }}</a> {{ author.date_of_birth }} - {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors registered.</p>
  {% endif %}       
{% endblock %}

src/locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <!--
      this is based on BookDetailView, which exposes a single Book object as the `book`.
      from there, we can then take the fields of the model as shown below

      from mdn:
      That's it! All you need to do now is create a template called /locallibrary/catalog/templates/catalog/book_detail.html, 
      and the view will pass it the database information for the specific Book record extracted by the URL mapper. 
      Within the template you can access the list of books with the template variable named object OR book 
      (i.e. generically "the_model_name").
  -->
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p> 
<p><strong>Language:</strong> {{ book.language }}</p>  
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>  

<div style="margin-left:20px;margin-top:20px">
  <h4>Copies</h4>
  <!--
    book.bookinstance_set.all is a django-constructed iterable of every BookInstance object associated with a Book
    this allows us to expose its fields and generate the list of book instances shown below
  -->
  {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
      {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
      <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
  {% endfor %}
</div>
{% endblock %}

src/locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

src/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

src/locallibrary/catalog/templates/catalog/borrowed_books_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) - {{ bookinst.borrower }}    
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}